### ISSUE TITLE
[API 문서] 내용 다듬기

### ISSUE THREAD

**Issue by Mong-Gu** [boostcamp-2020/Project16-D-Account-Book#263]
- 현재 GET 요청 변수 정보가 빠져있는 곳을 몇 개 발견했습니다.
- 메서드가 실제 API와 다르게 기재되어 있는 것을 몇 개 발견하여 수정했습니다.

위 내용과 더불어 오탈자 검토 등 마지막 주간에 API 문서를 전체적으로 다듬어야 할 필요가 있어보입니다.

- [x] 유저 (User)
- [x] 가계부 (Accountbook)
- [x] 소셜 (Social)
- [x] 거래 내역 (Transaction)
- [x] 카테고리 (Category)
- [x] 계좌/결제수단 (Account)

**Comment by mu1616** [comment]
확인했습니다!

**Comment by Mong-Gu** [comment]
@mu1616 @bbbyung2 @lacomaco 

slack에서 관리하던 것을 여기로 옮겼습니다. 주말에 작업합시다!
