### ISSUE TITLE
[문서] README 수정

### ISSUE THREAD

**Issue by Mong-Gu** [boostcamp-2020/Project16-D-Account-Book#276]
## 🥇  목표
WIKI에 네이버 애플리케이션 등록 방법과 카카오 애플리케이션 등록 방법을 새로운 페이지에 작성한 후, README에 링크를 걸어둔다.

- [ ] 네이버 애플리케이션 등록 방법 @Mong-Gu 
- [ ] 카카오 애플리케이션 등록 방법 @bbbyung2

**Comment by Mong-Gu** [comment]
@bbbyung2 내일 진ㅉㅏ 합시다 병화님...

**Comment by bbbyung2** [comment]
앗 알겠습니다,,

**Comment by Mong-Gu** [comment]
결국 하지 못하고 이 이슈는 닫히는 걸로...
