### ISSUE TITLE
[공통] 네이버 로그인 오류

### ISSUE THREAD

**Issue by Mong-Gu** [boostcamp-2020/Project16-D-Account-Book#287]
## 🥇  목표
- 네이버 로그인 시 발생하는 다음과 같은 에러(`protocol is prohibited`)에 대해 처리하는 방법을 탐색해보고 해결하도록 한다. 구글링해도 전혀 나오지 않는 것을 보니 네이버에 직접 문의를 하는 것이 제일 빠를 것 같다.

![image](https://user-images.githubusercontent.com/46754917/102022425-13cfb680-3dca-11eb-87f0-d9a11b15c4ca.png)

- 나와 민수님은 chrome에서 로그인이 잘 되고, edge에서 위 오류가 발생
- 영근님은 chrome에서 로그인 되지 않음
- 병화님은 chrome에서 로그인되지 않고, 사파리에서 로그인 잘 됨

**Comment by Mong-Gu** [comment]
일단 정상적인 것인지는 모르겠지만 다음과 같이 하면 로그인이 가능해지긴 한다.

1. [네이버](https://www.naver.com)에서 모아 서비스에 로그인했던 아이디로 로그인을 한다.
2. 내정보 - 보안설정 - [네이버와 연결된 서비스 관리](https://nid.naver.com/user2/help/externalAuth.nhn?lang=ko_KR) 순서대로 이동
3. '모아' 서비스 철회하기 클릭
4. [모아](http://moa.r-e.kr/login)에서 네이버 로그인 다시 해보기

이 방법의 문제는 애초부터 로그인 한 번 해보지 못하고 protocol is prohibited가 뜨는 경우다. 그러면 철회할 서비스조차 생기지 않기 때문... 현재 영근님과 나는 처리되었는데, 병화님은 계속 안 된다.

**Comment by bbbyung2** [comment]
저도 오류 해결됐습니다..하하
위와 같은 방법으로 '모아-테스트' 철회하고 재로그인했더니 해결됐습니다.

**Comment by Mong-Gu** [comment]
모아 모야 . . .

**Comment by Mong-Gu** [comment]
일단 close 하겠습니다 모두 해결되셨다고 하니!
