### ISSUE TITLE
[공통] 네이버 서비스 검수 요청

### ISSUE THREAD

**Issue by Mong-Gu** [boostcamp-2020/Project16-D-Account-Book#293]
## 🥇  목표
네이버의 아이디로 로그인 서비스 '네아로'를 활용하기 위한 서비스 검수 요청을 신청하고, 승인을 받는다.

- 2020.12.14 오후 6시 기준, 신청 완료

- 검수 기준 1 `제공 정보 활용처 확인`를 만족시키기 위한 첨부 파일
![](https://i.imgur.com/z9M7sFy.png)

- 검수 기준 2 `서비스 적용 형태 확인`를 만족시키기 위한 첨부 파일
![](https://i.imgur.com/MaGjDTG.png)

**Comment by Mong-Gu** [comment]
2020.12.15 오후 6시 7분 검수 요청에 대한 답변
![](https://i.imgur.com/hjyxqP0.png)

원인: 네아로를 적용하시려는 서비스에 대해 설명 또는 소개자료를 더 첨부해야 한다. 어떤 서비스인지 구체적인 설명 또는 소개자료(형식무관)를 추가하여야 함.

2020.12.15 오후 10시 30분 재검수요청 완료

**Comment by Mong-Gu** [comment]
2020.12.16 오후 3시 17분 검수 요청에 대한 답변

![](https://i.imgur.com/yfElVYh.png)

원인: 서비스 운영이 아닌 목적(과제, 데모, 테스트 등)으로 사전검수를 등록하셨다면 사전검수 없이 "개발중" 상태로 이용하라고 하신다. "개발중" 상태에서도 애플리케이션을 등록한 아이디와 테스터/관리자로 등록된 아이디(링크 참고)로 네아로를 이용할 수 있기 때문이다.

다시 제출한 소명 자료: [자료](https://www.dropbox.com/s/lmo8vwg50uk5ktt/%EA%B2%80%EC%88%98%20%EC%8A%B9%EC%9D%B8%EC%9D%B4%20%ED%95%84%EC%9A%94%ED%95%9C%20%EC%9D%B4%EC%9C%A0.pdf?dl=0)

**Comment by mu1616** [comment]
ㅠㅠ

**Comment by Mong-Gu** [comment]
![image](https://user-images.githubusercontent.com/46754917/104597531-cab89e00-56b8-11eb-9920-0032bf5543a7.png)
12/22 화요일... 승인 완료... ^_ㅠ
