### ISSUE TITLE
콘솔에 나오는 mobx warnings  제거하기

### ISSUE THREAD

**Issue by mu1616** [boostcamp-2020/Project16-D-Account-Book#338]
## 🥇  목표
- action 으로 안감싸고 상태를 변경하면 아래와 같은 warning이 발생하는데 이것을 없애자
![image](https://user-images.githubusercontent.com/26829633/102338650-7c3fb300-3fd7-11eb-95c1-6150c4e0ceae.png)

**Comment by Mong-Gu** [comment]
@mu1616 해결된 것 같아 보였는데 close하겠습니다!
