### ISSUE TITLE
달력 페이지 시간 이동 버그 

### ISSUE THREAD

**Issue by lacomaco** [boostcamp-2020/Project16-D-Account-Book#349]
![버그버그](https://user-images.githubusercontent.com/49854357/102458458-a05acd00-4087-11eb-8d01-3ef363c2c0bd.png)

2020.12 월에서

2021.1 월로 이동후
이전 달로 이동하기를 누르면

2019.12 월로 이동하게 되는 버그 존재

빠른 시일 내에 해결할것!!!!

**Comment by Mong-Gu** [comment]
@mu1616 이게 #360 과 같은 건가요 민수님?
